# Generated by Django 3.0.8 on 2020-08-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=30, verbose_name='Название зоны')),
                ('name_eng', models.CharField(max_length=30, verbose_name='Название зоны на английском')),
                ('area_value', models.CharField(max_length=30, verbose_name='Значение в м2')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(blank=True, upload_to='Cases/', verbose_name='Превью')),
                ('title_ru', models.CharField(max_length=30, verbose_name='Название проекта')),
                ('title_eng', models.CharField(max_length=30, verbose_name='Название проекта на английском')),
                ('short_descrition_ru', models.CharField(max_length=30, verbose_name='Краткое писание проекта')),
                ('short_descrition_eng',
                 models.CharField(max_length=30, verbose_name='Краткое описание проекта на английском')),
                ('descrition_ru', models.TextField(max_length=500, verbose_name='Описание проекта')),
                ('descrition_eng', models.TextField(max_length=500, verbose_name='Описание проекта на английском')),
                ('price_rub', models.IntegerField(verbose_name='Цена в рублях')),
                ('price_usd', models.IntegerField(verbose_name='Цена в $')),
                ('Style_ru', models.CharField(max_length=30, verbose_name='Стиль проекта')),
                ('style_eng', models.CharField(max_length=30, verbose_name='Стиль проекта на английском')),
                ('year', models.IntegerField(
                    choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989),
                             (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995),
                             (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001),
                             (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007),
                             (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013),
                             (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019),
                             (2020, 2020)], default=2020, verbose_name='Год проекта')),
                ('project_plan', models.ImageField(blank=True, upload_to='Cases/', verbose_name='План проекта')),
                ('areas', models.ManyToManyField(to='POPLAVSKY.Area', verbose_name='Площади')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=30, verbose_name='Название категрии')),
                ('name_eng', models.CharField(max_length=30, verbose_name='Название категрии на английском')),
            ],
            options={
                'verbose_name': 'Категория элемента портфолио',
                'verbose_name_plural': 'Категории элементов портфолио',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=30, verbose_name='Название')),
                ('name_eng', models.CharField(max_length=30, verbose_name='Название на английском')),
                ('image', models.ImageField(blank=True, upload_to='Partners/', verbose_name='Лого партнёра')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=30, verbose_name='Название комнаты')),
                ('name_eng', models.CharField(max_length=30, verbose_name='Название комнаты на английском')),
                ('image', models.ImageField(blank=True, upload_to='Rooms/', verbose_name='Изображение')),
                ('room_descrition_ru', models.TextField(max_length=500, verbose_name='Описание комнаты')),
                (
                    'room_descrition_eng',
                    models.TextField(max_length=500, verbose_name='Описание комнаты на английском')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон для заказчиков')),
                ('phone_office', models.CharField(max_length=12, verbose_name='телефон офиса')),
                ('mail', models.CharField(max_length=50, verbose_name='почта')),
                ('vk_link', models.CharField(max_length=50, verbose_name='Ссылка вконтакте')),
                ('instagram_link', models.CharField(max_length=50, verbose_name='Ссылка Instagram')),
                ('telegram_link', models.CharField(max_length=50, verbose_name='Ссылка Telegram')),
                ('houzz_link', models.CharField(max_length=50, verbose_name='Ссылка Houzz')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=30, verbose_name='Имя')),
                ('name_eng', models.CharField(max_length=30, verbose_name='Имя на английском')),
                ('title_ru', models.CharField(max_length=30, verbose_name='Должность')),
                ('title_eng', models.CharField(max_length=30, verbose_name='Должность на английском')),
                ('image', models.ImageField(blank=True, upload_to='Team/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Наша комнада',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('title_ru', models.CharField(max_length=30, verbose_name='Должность')),
                ('title_eng', models.CharField(max_length=30, verbose_name='Должность на английском')),
                ('image', models.ImageField(blank=True, upload_to='Clients/', verbose_name='Фото клиента')),
                ('review_title_ru', models.CharField(max_length=30, verbose_name='Заголовок отзыва')),
                ('review_body_ru', models.TextField(verbose_name='Отзыв')),
                ('review_title_eng', models.CharField(max_length=30, verbose_name='Заголовок отзыва на англипйском')),
                ('review_body_eng', models.TextField(verbose_name='Отзыв на английском')),
                ('project',
                 models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='POPLAVSKY.Case',
                                   verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POPLAVSKY.CaseCategory',
                                    verbose_name='Категория'),
        ),
    ]
