# Generated by Django 3.0.8 on 2020-09-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('POPLAVSKY', '0002_auto_20200909_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='POPLAVSKY.Case', verbose_name='Проект'),
        ),
    ]
