# Generated by Django 3.0.8 on 2020-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('POPLAVSKY', '0003_auto_20200909_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='display_on_site',
            field=models.BooleanField(default=True, verbose_name='Отображать на сайте'),
        ),
        migrations.AddField(
            model_name='partners',
            name='display_on_site',
            field=models.BooleanField(default=True, verbose_name='Отображать на сайте'),
        ),
        migrations.AddField(
            model_name='review',
            name='display_on_site',
            field=models.BooleanField(default=True, verbose_name='Отображать на сайте'),
        ),
        migrations.AddField(
            model_name='worker',
            name='display_on_site',
            field=models.BooleanField(default=True, verbose_name='Отображать на сайте'),
        ),
    ]
