# Generated by Django 3.0.8 on 2020-09-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('POPLAVSKY', '0004_auto_20200909_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='short_descrition_eng',
            field=models.TextField(max_length=300, verbose_name='Краткое описание проекта на английском'),
        ),
        migrations.AlterField(
            model_name='case',
            name='short_descrition_ru',
            field=models.TextField(max_length=300, verbose_name='Краткое писание проекта'),
        ),
    ]
