# Generated by Django 3.0.8 on 2020-09-09 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('POPLAVSKY', '0005_auto_20200909_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='location_eng',
            field=models.CharField(default='1', max_length=30, verbose_name='Лоцакия на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='location_ru',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Лоцакия'),
            preserve_default=False,
        ),
    ]
