# Generated by Django 3.0.8 on 2020-09-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('POPLAVSKY', '0007_case_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casecategory',
            options={'verbose_name': 'Категория портфолио', 'verbose_name_plural': 'Категории портфолио'},
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='meta_words',
            field=models.TextField(default='q', verbose_name='Ключевые слова в формате - "some, key, words"'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='massage',
            field=models.TextField(blank=True, verbose_name='Сообщение   '),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
    ]
