# Generated by Django 3.1 on 2020-10-05 19:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('POPLAVSKY', '0008_auto_20200909_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='Style_ru',
            new_name='style_ru',
        ),
        migrations.AlterField(
            model_name='review',
            name='review_body_eng',
            field=tinymce.models.HTMLField(verbose_name='Отзыв на английском'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_body_ru',
            field=tinymce.models.HTMLField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_title_eng',
            field=models.CharField(max_length=200, verbose_name='Заголовок отзыва на англипйском'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_title_ru',
            field=models.CharField(max_length=200, verbose_name='Заголовок отзыва'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='meta_words',
            field=models.TextField(blank=True, verbose_name='Ключевые слова в формате: "some, key, words"'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Телефон для заказчиков'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone_office',
            field=models.CharField(max_length=16, verbose_name='телефон офиса'),
        ),
    ]
