# Generated by Django 3.1 on 2020-10-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POPLAVSKY', '0009_auto_20201005_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='seo_dictinary',
            field=models.TextField(default='1', verbose_name='SEO keywords (через запятую) '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='is_active',
            field=models.BooleanField(default='1', verbose_name='Включены'),
            preserve_default=False,
        ),
    ]
