# Generated by Django 3.1 on 2020-10-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POPLAVSKY', '0010_auto_20201005_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='descr',
            field=models.TextField(blank=True, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='descr_eng',
            field=models.TextField(blank=True, verbose_name='SEO описание'),
        ),
    ]
