# Generated by Django 3.1 on 2020-10-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POPLAVSKY', '0011_auto_20201005_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='question_or_request',
        ),
        migrations.AddField(
            model_name='request',
            name='from_page',
            field=models.CharField(default='1', editable=False, max_length=100, verbose_name='Заявка из'),
        ),
    ]
