# Generated by Django 3.1 on 2020-10-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POPLAVSKY', '0012_auto_20201011_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.CharField(editable=False, max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='request',
            name='massage',
            field=models.TextField(blank=True, editable=False, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(editable=False, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(blank=True, default='Без номера телефона', editable=False, max_length=25, verbose_name='Телефон'),
        ),
    ]
