# Generated by Django 3.1 on 2020-10-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POPLAVSKY', '0013_auto_20201011_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name_eng',
            field=models.CharField(default=' ', max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='request',
            name='massage',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='descr_eng',
            field=models.TextField(blank=True, verbose_name='SEO описание на английском'),
        ),
    ]
